model:
  arch: mini_gpt4
  model_type: pretrain_vicuna
  freeze_vit: True
  freeze_qformer: True
  max_txt_len: 256
  end_sym: "###"
  prompt_template: '###Human: {} ###Assistant: '\
  ckpt: '/home/ubuntu/ProteinGPT/minigpt4/IT/Llama-2-7b-chat-hf/checkpoint.pth'


datasets:
  cc_sbu_align:
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"

run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-5
  min_lr: 1e-6
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 10
  # iters_per_epoch: 762
  batch_size_train: 1
  batch_size_eval: 1
  num_workers: 12
  warmup_steps: 5000

  seed: 42
  output_dir: "ft/Meta-Llama-3-8B-Instruct-hf/"

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
  stage: 2
